### ISSUE TITLE
Can you add bump-mapping and/or jackal shield turning red?

### ISSUE THREAD

**Issue by Rockship2910** [SnowyMouse/chimera#104]
also make cortana red when angry. Basically I'm asking you to do the fix that 343 did to halo ce

**Comment by MrChromed** [comment]
For bump mapping and other fixes for CE, you can download "CEnshine":
[https://youtu.be/0egQ3MYwx7Y](url)

As for the Jackal and Cortana, you can download the "Halo CE Refined" project: 
[http://vaporeon.io/hosted/halo/refined/halo_refined_custom_edition_en_v3rc2.7z](url)

**Comment by Rockship2910** [comment]
Thanks MrChromed

**Comment by Rockship2910** [comment]
Wait but it didn't work, it said something about segmentation fault. Any fixes? (refined) and the bumpmaping does not work (censhine)

**Comment by Rockship2910** [comment]
I had to make one .bin and have both in to work

**Comment by Rockship2910** [comment]
nope nevermind still is broken

**Comment by MrChromed** [comment]
Keep in mind that CEnshine is ONLY compatible with Halo Custom Edition, in case you're using Halo Combat Evolved/Retail.
