### ISSUE TITLE
micro stuttering

### ISSUE THREAD

**Issue by fenderjaguarnet** [SnowyMouse/chimera#106]
anyone noticed that there is micro stuttering, very similar to the kind you used to get with running multiple gpu in ati crossfire?

tried in all refresh rates, all frame rates, throttle_fps, vsync off/on, gsync, no sync etc

**Comment by fenderjaguarnet** [comment]
really, nobody else is getting this? it's really bad. also, I notice it doesn't work with freesync

**Comment by Aerocatia** [comment]
No, I don't get this. If you are not already you should be using maps in RAM with a LAA patched EXE. The stock game stalls on IO and that can cause issues.

**Comment by PseudoProxen** [comment]
That's what aero is pointing out, the game is very i/o hard drive wise in its vanilla form and the games framerate/tickrate is cpu bound. So it can still bottleneck itself even on high end machines when it is trying to i/o the information due to the executable process. Loading from ram 'helps' deviate it.

**Comment by Cambidd** [comment]
I've noticed this as well. Drove me nuts. The sort of "jitter" thats most noticeable when jumping. Specifically, releases that I've downloaded from github do it, however builds that I've compiled locally don't seem to have this problem for whatever reason (build tools?)

**Comment by PseudoProxen** [comment]
Wondering if git build is having some issues then ...

**Comment by Cambidd** [comment]
[strings.zip](https://github.com/SnowyMouse/chimera/files/13731282/strings.zip)
Try this build that I compiled locally to see if I'm not going mad.

**Comment by fenderjaguarnet** [comment]
> [strings.zip](https://github.com/SnowyMouse/chimera/files/13731282/strings.zip) Try this build that I compiled locally to see if I'm not going mad.

thanks! one thing I notice about that strings.dll you compiled, is that the console writing is now native resolution

but the freesync jitter is still there. with the stock halo pc strings.dll it's perfectly fluid

**Comment by fenderjaguarnet** [comment]
> Also what os are you on, and are you utilizing any DIrectX Wrappers. (DgVoodoo2, GoG, Vulkin, etc)

no, I'm using DX9 with shader model 1.4 (-use14) for the glass shaders. but it's the same in shader 2.0. on windows 10

**Comment by fenderjaguarnet** [comment]
seems to especially happen when you're walking up from here:

![436545](https://github.com/SnowyMouse/chimera/assets/143359451/e18e4009-aa96-4632-bdee-66bfbe5709a9)

**Comment by PseudoProxen** [comment]
That would be a save point area and also probably loading another portion of the map. So leads back to the i/o from the hard drive/sdd.

Are you utilizing the load map into memory flag?

**Comment by PseudoProxen** [comment]
Really no way to bypass that either, just old code and how it works. You can see it slightly stutter due to the bsp loading sections of maps.

Example video
https://www.proxeninc.net/Halo/Screens/Halo_2023-12-20.mp4

**Comment by fenderjaguarnet** [comment]
> That would be a save point area and also probably loading another portion of the map. So leads back to the i/o from the hard drive/sdd.
> 
> Are you utilizing the load map into memory flag?

I appreciate that you think this, and the "loading/save" screen gives a very minor 1 frame stutter, but it's not this. thank you anway

I have solved the issue, and it's a combination of 2 things. first the stuttering when walking upwards/jumping is caused by not being capped at 30 fps intervals (it's fine when I cap at 30, 60, 90, 120 etc etc).

secondly, if I use DXVK as a wrapper, I can use freesync and it's very smooth. freesync doesn't seem to work with the normal renderer. also, I had no idea DXVK boost performance so much, also I don't see why buffering is considered "bullshit" by the devs of chimera, since it doubles the frame rate

**Comment by PseudoProxen** [comment]
Yeah the hardcoded tick rate, with everything running around it; basically is the cause of it all. So in a nutshell we are technically all correct, cause i/o is just a small part of the bigger issue. But yes intervals of 30 are prime for this game, there is a more accurate number for it little below it due to programs cycling of code but that’s a different topic all together

**Comment by Aerocatia** [comment]
buffering introduces mouse lag and does not increase frame rate on anything that is not DXVK, and mind you blocking that and adding it to the bullshit list was done long before DXVK had d3d9 support.

Regarding native d3d9, that has been bitrotting for years on most major GPU drivers, it should not be used.

**Comment by Aerocatia** [comment]
I removed it from `chimera_block_all_bullshit` in 9536774ff73bc46e17aab6e8cc8851a83c818199

**Comment by fenderjaguarnet** [comment]
> buffering introduces mouse lag and does not increase frame rate on anything that is not DXVK, and mind you blocking that and adding it to the bullshit list was done long before DXVK had d3d9 support.

thank you for your post

whilst it's possible it could cause input lag, I'm actually pretty sceptical of it. are we sure this isn't just something that's been repeated over and over the years, because somebody said it once, with no proof? i'd love to see it tested with buffering on .vs buffering off, capped at the same frame rate. 

I'm pretty sensitive to input lag myself. for example when I enabled vsync on 120hz and capped at 120fps with rivatuner to decrease the input lag, I really disliked it. it wasn't super laggy, it's just I usually use nosync, but when the frame pacing is so bad like that, I enable freesync.

I also notice that the chimera fps capping "chimera_throttle_fps" has more input lag than capping with rivatuner or nvidia drivers, and using dgvoodoo2 renderer capping. usually game engines have more control over the code necessary to cap frame rate in a low latency manner, but it's not always the case

**Comment by SnowyMouse** [comment]
Message ID: ***@***.***>Yeah, unfortunately the game being closed source limits the scope of what mods like Chimera can do and what we are capable of changing.

The frame rate limiting method is just a dumb sleep function, so of course your input lag will be increased.

And of course, interpolation is a bit hacky as it is, and as much as I'd love to improve it, it has become incredibly difficult for me to work with the game like this, so a decomp of the game might be what we really need eventually.
