### ISSUE TITLE
HUD Safe Area Feature

### ISSUE THREAD

**Issue by JS299990** [SnowyMouse/chimera#121]
Hello awesome devs, I don't know if you are open to user requests or not. But if you are, could you please consider adding a "Safe Zone" feature for the HUD? Something that places the HUD elements a bit closer to the center of the screen, just like in the original console version. Or a new preset for the `chimera_widescreen_fix` command that achieves the same look maybe?

Here's a picture what I mean: 

![HALO](https://github.com/user-attachments/assets/de9f32e7-d6e5-482d-9df8-1f7f85176495)

Even though I do think it looks cooler that way, I'm asking this for more practical reasons. I never noticed before that the PC version had the HUD pushed all the way to the corners of the screen and when I went to replay the OG console version today after not having played it for many years, the last thing I thought I would've noticed was HUD, but hey, it's just straight up better ¯\_(ツ)_/¯ all the info is shoved directly into your eyes. It would be cool to have this in the PC version.

Either way thank you all for the continuous effort on this project. It's amazing.

**Comment by MangoFizz** [comment]
Some time ago Snowy released a Lua script for that, you can find it in this post on Open Carnage:
[https://opencarnage.net/index.php?/topic/8193-safe-zones/](https://opencarnage.net/index.php?/topic/8193-safe-zones/)

**Comment by JS299990** [comment]
> Some time ago Snowy released a Lua script for that, you can find it in this post on Open Carnage: https://opencarnage.net/index.php?/topic/8193-safe-zones/

![image](https://github.com/user-attachments/assets/fc4f8bca-ec9b-4013-aaa2-5c06afb9221b)

Many thanks for your reply but it seems I'm unable to access this website though. I'm not using a VPN or anything.

**Comment by JS299990** [comment]
> Some time ago Snowy released a Lua script for that, you can find it in this post on Open Carnage: https://opencarnage.net/index.php?/topic/8193-safe-zones/

Many thanks! Works like a charm!
