### ISSUE TITLE
English localization missing keys

### ISSUE THREAD

**Issue by BinToss** [SnowyMouse/chimera#69]
https://github.com/SnowyMouse/chimera/blob/21deabad1527181c6aa6e7aa9317a6acf9a6cfbf/src/chimera/localization/language/0#L197-L222

```
chimera_spam_to_join_command_help 
chimera_spam_to_join_retrying     

chimera_lua_error_draw_text_invalid_alignment
chimera_lua_error_draw_text_invalid_font_id
chimera_lua_error_expected_number
chimera_lua_error_expected_number_or_boolean
chimera_lua_error_global_not_found
chimera_lua_error_invalid_callback
chimera_lua_error_invalid_function_argument
chimera_lua_error_invalid_object_id
chimera_lua_error_invalid_timer_argument
chimera_lua_error_minimum_tick_rate
chimera_lua_error_minimum_timer_interval
chimera_lua_error_scope_path
chimera_lua_error_script_sandbox_invalid_address
chimera_lua_error_spawn_object_invalid_id
chimera_lua_error_spawn_object_invalid_path
chimera_lua_error_timer_does_not_exists
chimera_lua_error_wrong_number_of_arguments
chimera_lua_warning_script_undefined_api_version
chimera_lua_error_scope_path
```

**Comment by JerryBrick** [comment]
I think you mean the missing keys in the Spanish language. About it... I'm not sure about translating the Lua API errors. Lua itself is not multilanguage so translating those messages would be a little inconsistent.

The spam to join messages are already translated.
https://github.com/SnowyMouse/chimera/blob/21deabad1527181c6aa6e7aa9317a6acf9a6cfbf/src/chimera/localization/language/1#L201-L202

**Comment by BinToss** [comment]
Interesting, but these missing string errors were thrown by the compiler.
...
I see. The strings *are* present in the English locale. I wonder why the compiler was complaining...
