### ISSUE TITLE
Reimplement strings.dll's exception strings

### ISSUE THREAD

**Issue by BinToss** [SnowyMouse/chimera#76]
- [ ] Make a list of all the string resources in strings.dll.
- [ ] Figure out how Halo accesses those string. Does it load the resources from the assembly or access them some other way?

**Comment by BinToss** [comment]
https://drive.google.com/file/d/1aOVTIJPRjI09TposPqRs6g8xJJZyAsUl/view?usp=sharing
A rundown of the Custom Edition 1.0.10 strings.dll
Every string is stored as a Resource.

**Comment by BinToss** [comment]
Possible solutions:
### A - Copy resources during compiletime
Compile strings and bitmap resources into Chimera binary during compile-time.
### B - Copy resources during runtime
Modify Chimera binary during runtime. Copy resources from strings-old.dll/strings.gearbox.dll to chimera's strings.dll
### C - Patcher
Provide patcher app to users. Patch Chimera into stock strings.dll (!!! may violate Microsoft code sig). What if user's strings.dll is older Chimera? Do we patch stock resources into it?

**Comment by JerryBrick** [comment]
Interesting, I think solution A is the right way to go, I'll take a look at it later. Thank you!

**Comment by BinToss** [comment]
I tested the theory via ResourceHacker tonight.
Transplanting the string resources does work. I used an SPV3 strings.dll as the donor and a Monolith 1.0.5 as the recipient.
![image](https://user-images.githubusercontent.com/7243190/184492790-a16a0259-3677-4ca4-970b-f1428102e8d6.png)

**Comment by Vaporeon** [comment]
I see.

**Comment by Vaporeon** [comment]
If you include the halo bitmap, the original splash screen works too.

**Comment by BinToss** [comment]
Speaking of the loading screen bitmap, could we consider loading an external bitmap for loading screen customization that doesn't require modifying patching a DLL with a new bitmap?

**Comment by Vaporeon** [comment]
Fixed in 00d2fa7ed0d0f315aed374a3dd8ef79a82438805

**Comment by Vaporeon** [comment]
@BinToss A custom bitmap loaded at runtime could be possible, but it would be a low priority to implement this I'd say.

**Comment by BinToss** [comment]
That's fine with me. I can't imagine anyone using it other than for memes or for stuff like SPV3.
