### ISSUE TITLE
Automatic map downloading is not working

### ISSUE THREAD

**Issue by dwilhel1** [SnowyMouse/chimera#91]
My Chimera install no longer automatically downloads new maps, failing with the error message "The address is invalid".

Unsure of how to troubleshoot. Happy to collab on this one.

**Edit:** Verified the HAC2 map repository base URL is returning 200 response codes: http://maps.halonet.net

![image](https://user-images.githubusercontent.com/14366454/188053724-22a45e6c-6a25-4d27-8edd-f809196bcccd.png)

**Comment by BinToss** [comment]
Wild guess: the HAC2 map repository is down.

**Comment by pR0Ps** [comment]
It's not down, but the endpoint that Chimera uses to download maps in `*.inv` format is currently returning corrupted data.

As far as I know, downloading maps as `*.zip` and `*.7z` archives is still working.

@Vaporeon has reached out to the maintainer of the repo to see of they can fix it.

**Comment by PseudoProxen** [comment]
This should be fixed as of now after 933

**Comment by MangoFizz** [comment]
Yep, it was fixed on [32bcb4a](https://github.com/SnowyMouse/chimera/commit/32bcb4adcbf9dc546ab9e1435cbfb0e95f297f46).
